app/data/forms.py
"""
Qrater Data Management.

Module with blueprint specific Forms
"""

from flask_wtf import FlaskForm
from wtforms import (StringField, SubmitField, MultipleFileField, SelectField,
                     SelectMultipleField, BooleanField, RadioField)
from wtforms.validators import DataRequired, ValidationError
from app.models import Dataset


class LoadDatasetForm(FlaskForm):
    """Form for loading a new dataset from within host."""

    dir_name = SelectField("Directory", validators=[DataRequired()])
    submit = SubmitField('Load')


class UploadDatasetForm(FlaskForm):
    """Form for uploading a new dataset."""

    dataset_name = StringField("Dataset's name", validators=[DataRequired()])
    privacy = BooleanField("Private")
    dataset = MultipleFileField('MRI files', validators=[DataRequired()])
    submit = SubmitField('Upload')

    def validate_dataset_name(self, dataset_name):
        """Check that the dataset's name does not already exist."""
        ncheck = Dataset.query.filter_by(name=dataset_name.data).first()
        if ncheck is not None:
            raise ValidationError(
                f'A Dataset named "{ncheck.name}" already exists.')


class EditDatasetForm(FlaskForm):
    """Form for editing an existing dataset."""

    dataset = SelectField("Dataset", validators=[DataRequired()])
    new_name = StringField("Dataset's name")
    privacy = BooleanField("Private")

    # This can only be edited in the BACKEND:
    share_ratings = BooleanField("Sharing")

    # Precomments/Subratings:
    # Concatenated strings with '___'
    sr_change = BooleanField("Subratings")
    sr_ids = StringField("IDs")
    sr_texts = StringField("Precomment")
    sr_ratings = StringField("Rating")
    sr_keybindings = StringField("KeyBinding")

    # Choices for this will be generated in the route
    viewers = SelectMultipleField("Raters", coerce=int)
    sub_regex = StringField("Subjects' label (regex)")
    sess_regex = StringField("Sessions' label (regex)")
    cohort_regex = StringField("Cohort label (regex)")
    type_regex = StringField("Image type label (regex)")
    imgs_to_upload = MultipleFileField('MRI files')
    submit = SubmitField('Upload')

app/data/__init__.py
"""
Qrater Data management.

Construction of blueprint
"""

from flask import Blueprint

bp = Blueprint('data', __name__)

from app.data import routes

app/data/routes.py
"""
Qrater Data Management.

Module with blueprint specific routes
"""

import os
import re
from flask import (render_template, flash, redirect, url_for, request,
                   current_app)
from flask_login import login_required, current_user
from app import db
from app.data import bp
from app.models import Dataset, Rater, Precomment
from app.data.functions import load_data, upload_data
from app.data.forms import LoadDatasetForm, UploadDatasetForm, EditDatasetForm
from app.data.exceptions import (OrphanDatasetError, EmptyLoadError)


@bp.route('/upload-dataset', methods=['GET', 'POST'])
@login_required
def upload_dataset():
    """Page to upload new dataset of MRI."""
    data_dir = os.path.join(current_app.config['ABS_PATH'],
                            'static/datasets/uploaded')

    # All raters
    all_raters = request.args.get('all_raters', 0, type=int)

    form = UploadDatasetForm()
    if form.validate_on_submit():
        files = request.files.getlist(form.dataset.name)
        savedir = os.path.join(data_dir, form.dataset_name.data)

        # If savedir does not exist; create it
        if not os.path.isdir(savedir):
            os.makedirs(savedir)

        # Form checks that dataset does not exist already
        # so there is no need to check here; just create it
        dataset = Dataset(name=form.dataset_name.data,
                          creator=current_user,
                          private=form.privacy.data)
        dataset.grant_access(current_user)
        db.session.add(dataset)

        privacy = 'a PRIVATE' if dataset.private else 'an OPEN'
        flash(f"{dataset.name} was created as {privacy} dataset", 'info')

        if len(files) > 10:
            # Redis can't handle FileStorage
            # First upload all files
            files_uploaded = upload_data(files, savedir)
            current_user.launch_task('load_data',
                                     f'Uploading {len(files)} new images '
                                     f'to {dataset.name} dataset...',
                                     icon='upload',
                                     alert_color='primary',
                                     files=files_uploaded,
                                     dataset_name=dataset.name,
                                     new_dataset=True)
            db.session.commit()
        else:
            try:
                # Function returns number of uploaded images
                loaded_imgs = load_data(files, dataset, savedir=savedir)
            except OrphanDatasetError:
                # If orphaned dataset, delete it
                db.session.delete(dataset)
            else:
                # If not, that means at least one image was uploaded
                # flash success with number of uploads
                flash(f'{loaded_imgs} file(s) successfully loaded!', 'success')
            finally:
                # Commit changes in database
                db.session.commit()

        return redirect(url_for('main.dashboard', all_raters=all_raters))
    for _, error in form.errors.items():
        flash(error[0], 'danger')
    return render_template('data/upload_dataset.html', form=form,
                           all_raters=all_raters, title='Upload Dataset')


@bp.route('/load-dataset', methods=['GET', 'POST'])
@bp.route('/load-dataset/<directory>', methods=['GET', 'POST'])
@login_required
def load_dataset(directory=None):
    """Page to load new datasets from within HOST."""
    data_dir = os.path.join(current_app.config['ABS_PATH'],
                            'static/datasets/preloaded')

    # All raters
    all_raters = request.args.get('all_raters', 0, type=int)

    # Choices of directories to load in form
    dir_choices = [d for d in os.listdir(data_dir)
                   if os.path.isdir(os.path.join(data_dir, d))]
    dir_choices.sort()

    info = {'directory': directory, 'new_imgs': 0}
    if directory is not None:
        # Save useful info for jinja template
        info['model'] = Dataset.query.filter_by(name=directory).first()
        # Check access before loading files
        if info['model']:
            info['access'] = current_user.has_access(info['model'])
            info['saved_imgs'] = info['model'].images.count()
        else:
            info['access'] = True
            info['saved_imgs'] = 0

        if info['access']:
            # Count the files in the directory
            all_files = []
            for root, _, files in os.walk(os.path.join(data_dir, directory)):
                all_files.extend([os.path.join(root, f)
                                  for f in files if not f.startswith('.')])
            info['new_imgs'] = len(all_files) - info['saved_imgs']

    form = LoadDatasetForm()
    form.dir_name.choices = dir_choices

    # Form submission must be restricted by access in template
    if form.validate_on_submit():
        if info['model']:
            new_dataset = False
        else:
            # If dataset is not a Dataset Model (does not exist), create it
            info['model'] = Dataset(name=form.dir_name.data,
                                    creator=current_user)
            db.session.add(info['model'])
            new_dataset = True
            flash(f"{info['model'].name} was created as an OPEN dataset",
                  'info')

        if len(all_files) > 10:
            current_user.launch_task('load_data',
                                     f"Loading {info['new_imgs']} new images "
                                     f"to {info['model'].name} dataset...",
                                     icon='load',
                                     alert_color='primary',
                                     files=all_files,
                                     dataset_name=info['model'].name,
                                     new_dataset=new_dataset,
                                     ignore_existing=True)
            db.session.commit()

        else:
            try:
                # Function returns number of uploaded images
                loaded_imgs = load_data(all_files, dataset=info['model'],
                                        host=True, new_dataset=new_dataset)

            except OrphanDatasetError:
                # If orphaned dataset, delete it
                # TODO this somehow throws an error; look into this
                # db.session.delete(info['model'])
                flash('No new files were successfully loaded '
                      'leaving the dataset empty', 'warning')

            else:
                if not new_dataset and loaded_imgs == 0:
                    flash('No new files were successfully loaded', 'warning')
                else:
                    flash(f'{loaded_imgs} file(s) successfully loaded!',
                          'success')
            finally:
                # Commit changes in database
                db.session.commit()

        return redirect(url_for('main.dashboard', all_raters=all_raters))

    # Form validation errors
    for _, error in form.errors.items():
        flash(error[0], 'danger')

    return render_template('data/load_dataset.html', form=form,
                           title="Load Dataset", dictionary=info,
                           all_raters=all_raters)


@bp.route('/edit-dataset', methods=['GET', 'POST'])
@bp.route('/edit-dataset/<dataset>', methods=['GET', 'POST'])
@login_required
def edit_dataset(dataset=None):
    """Page to edit an existing dataset of MRI."""
    data_dir = os.path.join(current_app.config['ABS_PATH'], 'static/datasets')

    # All raters
    all_raters = request.args.get('all_raters', 0, type=int)

    # Read-only; Disable dataset loader when accessing through link
    ro = request.args.get('ro', 0, type=int)

    ds_model = Dataset.query.\
        filter_by(name=dataset).\
        first_or_404() \
        if dataset else None

    form = EditDatasetForm()
    if ro:
        form.dataset.data = dataset

    privacy = ds_model.private if ds_model else None
    public_ds = Dataset.query.filter_by(private=False)
    private_ds = Dataset.query.filter(Dataset.viewers.contains(current_user))
    form.dataset.choices = [ds.name for ds in public_ds.union(private_ds)]
    form.viewers.choices = [(r.id, r.username, r in ds_model.viewers)
                            for r in Rater.query.order_by('username')
                            if r not in [current_user, ds_model.creator]] \
        if dataset else []

    # Test image names for regex helper
    test_names = {}
    for set in Dataset.query.all():
        test_names[set.name] = [img.path for img in set.images.limit(5).all()]

    changes = False
    subratings = ds_model.subratings if ds_model else None
    if form.validate_on_submit():
        new_ds_name = None

        # Subratings;
        if form.sr_change.data:
            sr_ids, sr_texts, sr_ratings, sr_keybindings = (
                [id.split("_")[1] if id else ""
                 for id in form.sr_ids.data.split("___")],
                form.sr_texts.data.split("___"),
                form.sr_ratings.data.split("___"),
                form.sr_keybindings.data.split("___")
            )

            # Sanity check
            print(f"{sr_ids=} {sr_texts=} {sr_ratings=} {sr_keybindings=}")
            if not (len(sr_ids)
                    == len(sr_texts)
                    == len(sr_ratings)
                    == len(sr_keybindings)):
                flash(('Something went wrong trying to set up the '
                      'pre-defined ratings.'), 'danger')
                return redirect(request.url)

            for n, id in enumerate(sr_ids):
                if "d" in id:
                    print(f"{id=}")
                    sr = Precomment.query.filter_by(id=id[1:-1]).first()
                    print(f"{sr=}")
                    if sr:
                        db.session.delete(sr)
                else:
                    sr = Precomment(dataset=ds_model) if "n" in id \

app/dt/__init__.py
"""
Qrater DataTables.

Construction of blueprint
"""

from flask import Blueprint

bp = Blueprint('dt', __name__)

from app.dt import routes

app/dt/routes.py
"""
Qrater DataTables.

Module with blueprint specific routes
"""

from flask import jsonify, request, render_template, flash, redirect, url_for
from flask_login import current_user, login_required
from sqlalchemy import or_
from datatables import ColumnDT, DataTables
from app.models import db, Dataset, Image, Rating, Rater
from app.dt import bp


@bp.route('/datatable/<dataset>')
@login_required
def datatable(dataset):
    """List a table with the images and their ratings."""
    # Figure out how to send Dataset
    ds_model = Dataset.query.filter_by(name=dataset).first_or_404()
    all_raters = request.args.get('all_raters', 0, type=int)
    only_ratings = request.args.get('only_ratings', 0, type=int)

    # Double check sharing ratings
    all_raters = all_raters if ds_model.sharing else 0

    # Double check rater's access
    if not current_user.has_access(ds_model):
        flash(f"You don't have access to {dataset.name}", 'danger')
        all_raters_string = "all_raters" if all_raters else None
        return redirect(url_for('main.dashboard',
                                all_raters_string=all_raters_string))

    col_names = ['Type', 'Sub', 'Sess', 'Cohort', 'Rating', 'Comment']
    columns = {**dict.fromkeys(col_names, None)}

    columns['Type'] = bool(sum([bool(i.imgtype) for i in ds_model.images]))
    columns['Sub'] = bool(sum([bool(i.subject) for i in ds_model.images]))
    columns['Sess'] = bool(sum([bool(i.session) for i in ds_model.images]))
    columns['Cohort'] = bool(sum([bool(i.cohort) for i in ds_model.images]))
    columns['Rating'] = bool(sum([bool(i.ratings.all())
                                  for i in ds_model.images]))
    comments = [bool(r.comment) for r in
                Rating.query.join(Image).filter(Image.dataset == ds_model)]
    subratings = [bool(r.subratings.all()) for r in
                  Rating.query.join(Image).filter(Image.dataset == ds_model)]
    columns['Comment'] = (sum(comments) or sum(subratings))

    return render_template("dt/datatable.html", DS=ds_model,
                           types=columns['Type'], subs=columns['Sub'],
                           sess=columns['Sess'], cohorts=columns['Cohort'],
                           ratings=columns['Rating'], comms=columns['Comment'],
                           all_raters=all_raters, only_ratings=only_ratings)


@bp.route('/data/<int:dset_id>/<int:type>/<int:subject>/' +
          '<int:session>/<int:cohort>/<int:ratings>/' +
          '<int:comments>/<int:only_ratings>')
def data(dset_id, type, subject, session, cohort, ratings, comments,
         only_ratings=0):
    """Return server side data for datatable."""
    all_raters = request.args.get('all_raters', 0, type=int)

    columns = [
        ColumnDT(Image.name),
        ColumnDT(Rating.rating),
    ]

    # If there are ratings insert rating info
    if ratings:
        columns.insert(2, ColumnDT(Rating.timestamp))
        # TODO Figure out how to insert subratings here
        if comments:
            columns.insert(2, ColumnDT(Rating.comment))
        if all_raters:
            columns.insert(2, ColumnDT(Rater.username))

    # Check if there are cohort labels
    if cohort:
        columns.insert(1, ColumnDT(Image.cohort))

    # Check if there are sess labels
    if session:
        columns.insert(1, ColumnDT(Image.session))

    # Check if there are sub labels
    if subject:
        columns.insert(1, ColumnDT(Image.subject))

    # Check if there are type labels
    if type:
        columns.insert(1, ColumnDT(Image.imgtype))

    # Ratings query for single user (only ratings)
    if all_raters or current_user.is_anonymous:
        query = db.session.query().\
            select_from(Image).\
            filter(Image.dataset_id == dset_id,
                   Rating.rating > 0).\
            join(Rating).\
            join(Rater) if only_ratings \
            else db.session.query().\
            select_from(Image).\
            filter(Image.dataset_id == dset_id).\
            join(Rating, isouter=True).\
            join(Rater, isouter=True)
    else:
        if only_ratings:
            query = db.session.query().\
                select_from(Image).\
                filter(Image.dataset_id == dset_id,
                       Rating.rater == current_user,
                       Rating.rating > 0).\
                join(Rating).\
                join(Rater)
        else:
            query = db.session.query().\
                select_from(Image).\
                filter(Image.dataset_id == dset_id,
                       or_(Rating.rater == current_user,
                           Rating.rater == None)).\
                join(Rating, isouter=True).\
                join(Rater, isouter=True)

    params = request.args.to_dict()

    rowTable = DataTables(params, query, columns)
    return jsonify(rowTable.output_result())

app/templates/dt/datatable.html
{% extends 'base.html' %}

{% block styles %}
{{ super()  }}
<link
  rel="stylesheet"
  type="text/css"
  href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap5.min.css">
<link
  rel="stylesheet"
  type="text/css"
  href="https://cdn.datatables.net/buttons/1.7.0/css/buttons.bootstrap5.min.css">
{#
<link
  rel="stylesheet"
  type="text/css"
  href="https://cdn.datatables.net/responsive/2.2.7/css/responsive.bootstrap5.min.css">
<link
  rel="stylesheet"
  type="text/css"
  href="https://cdn.datatables.net/scroller/2.0.3/css/scroller.bootstrap5.min.css">
#}
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb m-0">
  <li class="breadcrumb-item">
    <a
      class="text-decoration-none text-light"
      href="#"
      >{{ DS.name }}</a>
  </li>
</ol>
{% endblock %}

{% block app_content %}
<div class="row">
  <div class="col-lg-12 my-3">
    {# <h2>DataTables 1.10.x example: Users and their address.</h2> #}
    <table id="dataTable" class="table" cellspacing="0" width="100%">
      <thead class="table-dark">
        <tr>
          <th class="image">Image name</th>
          {% if types %}<th class="type">Type</th>{% endif %}
          {% if subs %}<th class="subject">Subject</th>{% endif %}
          {% if sess %}<th class="session">Session</th>{% endif %}
          {% if cohorts %}<th class="cohort">Cohort</th>{% endif %}
          <th class="rating">Rating</th>
          {% if ratings -%}
          {% if all_raters %}<th class="rater">Rater</th>{% endif %}
          {% if comms %}<th class="comment">Comment</th>{% endif %}
          <th class="datetime">Rated on</th>
          {%- endif %}
        </tr>
      </thead>
      <tbody></tbody>
    </table>
  </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script
  type="text/javascript"
  src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js">
</script>
<script
  type="text/javascript"
  src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap5.min.js">
</script>
<script
  type="text/javascript"
  src="https://cdn.datatables.net/buttons/1.7.0/js/dataTables.buttons.min.js">
</script>
<script
  type="text/javascript"
  src="https://cdn.datatables.net/buttons/1.7.0/js/buttons.bootstrap5.min.js">
</script>
<script
  type="text/javascript"
  src="https://cdn.datatables.net/buttons/1.7.0/js/buttons.colVis.min.js">
</script>
{#
<script
  type="text/javascript"
  src="https://cdn.datatables.net/responsive/2.2.7/js/dataTables.responsive.min.js">
</script>
<script
  type="text/javascript"
  src="https://cdn.datatables.net/responsive/2.2.7/js/responsive.bootstrap5.min.js">
</script>
<script
  type="text/javascript"
  src="https://cdn.datatables.net/responsive/2.0.3/js/dataTables.scroller.min.js">
</script>
#}
<script type="text/javascript" charset="utf-8">
  $(document).ready(function () {
    var table = $('#dataTable').DataTable({
      "processing": true,
      "serverSide": true,
      "ajax": "{{ url_for('dt.data', dset_id=DS.id,
                  all_raters=all_raters, only_ratings=only_ratings,
                  type=types, subject=subs, session=sess, cohort=cohorts,
                  comments=comms, ratings=ratings) }}",
      "lengthChange": false,
      "lengthMenu": [
          [ 10, 25, 50, 100 ],
          [ '10 rows', '25 rows', '50 rows', '100 rows' ]
      ],
      "columnDefs": [
        {
          targets: "image",
          render: function ( data, type, row ) {
            if ( type === 'display' ) {
              {# NEED TO CHANGE IF rate_img URL CHANGES #}
              return "<a href='/rate/{{ DS.name }}" +
                "?all_raters={{ all_raters }}" +
                "&image=" + data +
                "' class='link-dark text-decoration-none fw-light'>" +
                data + "</a>"
            }
            return data;
          },
          searchable: true
        },
        { targets: '_all', searchable: false },
        {
          targets: "rating",
          render: function ( data, type, row ) {
            if ( type === 'display' ) {
              switch(data) {
                case 1:
                  return "<a href=" +
                    "{{ url_for('main.rate', rating_filter=1,
                          all_raters=all_raters, name_dataset=DS.name) }} "+
                    "' class='link-success text-decoration-none fw-light'" +
                    ">Pass</a>";
                  break;
                case 2:
                  return "<a href=" +
                    "{{ url_for('main.rate', rating_filter=2,
                          all_raters=all_raters, name_dataset=DS.name) }} "+
                    "' class='link-warning text-decoration-none fw-light'" +
                    ">Warning</a>";
                  break;
                case 3:
                  return "<a href=" +
                    "{{ url_for('main.rate', rating_filter=3,
                            all_raters=all_raters, name_dataset=DS.name) }} "+
                    "' class='link-danger text-decoration-none fw-light'" +
                    ">Fail</a>";
                  break;
                default:
                  return "<a href=" +
                    "{{ url_for('main.rate', rating_filter=0,
                            all_raters=all_raters, name_dataset=DS.name) }} "+
                    "' class='link-secondary text-decoration-none fw-light'" +
                    ">Pending</a>";
              }
            }
            return data;
          }
        },
        {
          targets: "type",
          render: function ( data, type, row ) {
            if ( type === 'display' ) {
                return data ? "<a href='/rate/{{ DS.name }}" +
                  "?type_filter=" + data +
                  "&all_raters={{ all_raters }}" +
                  "' class='link-dark text-decoration-none fw-light'>" +
                  data + "</a>":
                      '<span class="text-muted fw-light"> NA</span>';
            }
            return data;
          }
        },
        {
          targets: "subject",
          render: function ( data, type, row ) {
            if ( type === 'display' ) {
                return data ? "<a href='/rate/{{ DS.name }}" +
                  "?sub_filter=" + data +
                  "&all_raters={{ all_raters }}" +
                  "' class='link-dark text-decoration-none fw-light'>" +
                  data + "</a>":
                      '<span class="text-muted fw-light"> NA</span>';
            }
            return data;
          }
        },
        {
          targets: "cohort",
          render: function ( data, type, row ) {
            if ( type === 'display' ) {
                return data ? "<a href='/rate/{{ DS.name }}" +
                  "?cohort_filter=" + data +
                  "&all_raters={{ all_raters }}" +
                  "' class='link-dark text-decoration-none fw-light'>" +
                  data + "</a>":
                      '<span class="text-muted fw-light"> NA</span>';
            }
            return data;
          }
        },
        {
          targets: "session",
          render: function ( data, type, row ) {
            if ( type === 'display' ) {
                return data ? "<a href='/rate/{{ DS.name }}" +
                  "?sess_filter=" + data +
                  "&all_raters={{ all_raters }}" +
                  "' class='link-dark text-decoration-none fw-light'>" +
                  data + "</a>":
                      '<span class="text-muted fw-light"> NA</span>';
            }
            return data;
          }
        },
        {
          targets: "comment",
          render: function ( data, type, row ) {
            if ( type === 'display' ) {
              return data ? '<span class="fw-light">' + data + '</span>':
                '<span class="text-muted fw-light">...</span>';
            }
            return data;
          }
        },
        {
          targets: "rater",
          render: function ( data, type, row ) {
            if ( type === 'display' ) {
              return data ? "<a href='/rate/{{ DS.name }}" +
                "?rater_filter=" + data +
                "&all_raters={{ all_raters }}" +
                "' class='link-dark text-decoration-none fw-light'>" +
                data + "</a>":
                '<span class="text-muted fw-light"> Unrated</span>';
            }
            return data;
          }
        },
        {
          targets: "datetime",
          render: function ( data, type, row ) {
            return data ? '<span class="fw-light">' +
              moment(data).format('Y/MM/DD; HH:mm') + '</span>' :
              '<span class="text-muted fw-light"> Unrated</span>';
          }
        }
      ]
    });
    new $.fn.dataTable.Buttons( table, {
        buttons: [ 'pageLength', 'colvis' ]
    } );
    table.buttons().container()
    .appendTo( '#dataTable_wrapper .col-md-6:eq(0)' );
  });
</script>
{% endblock %}