app/data/forms.py
"""
Qrater Data Management.

Module with blueprint specific Forms
"""

from flask_wtf import FlaskForm
from wtforms import (StringField, SubmitField, MultipleFileField, SelectField,
                     SelectMultipleField, BooleanField, RadioField)
from wtforms.validators import DataRequired, ValidationError
from app.models import Dataset


class LoadDatasetForm(FlaskForm):
    """Form for loading a new dataset from within host."""

    dir_name = SelectField("Directory", validators=[DataRequired()])
    submit = SubmitField('Load')


class UploadDatasetForm(FlaskForm):
    """Form for uploading a new dataset."""

    dataset_name = StringField("Dataset's name", validators=[DataRequired()])
    privacy = BooleanField("Private")
    dataset = MultipleFileField('MRI files', validators=[DataRequired()])
    submit = SubmitField('Upload')

    def validate_dataset_name(self, dataset_name):
        """Check that the dataset's name does not already exist."""
        ncheck = Dataset.query.filter_by(name=dataset_name.data).first()
        if ncheck is not None:
            raise ValidationError(
                f'A Dataset named "{ncheck.name}" already exists.')


class EditDatasetForm(FlaskForm):
    """Form for editing an existing dataset."""

    dataset = SelectField("Dataset", validators=[DataRequired()])
    new_name = StringField("Dataset's name")
    privacy = BooleanField("Private")

    # This can only be edited in the BACKEND:
    share_ratings = BooleanField("Sharing")

    # Precomments/Subratings:
    # Concatenated strings with '___'
    sr_change = BooleanField("Subratings")
    sr_ids = StringField("IDs")
    sr_texts = StringField("Precomment")
    sr_ratings = StringField("Rating")
    sr_keybindings = StringField("KeyBinding")

    # Choices for this will be generated in the route
    viewers = SelectMultipleField("Raters", coerce=int)
    sub_regex = StringField("Subjects' label (regex)")
    sess_regex = StringField("Sessions' label (regex)")
    cohort_regex = StringField("Cohort label (regex)")
    type_regex = StringField("Image type label (regex)")
    imgs_to_upload = MultipleFileField('MRI files')
    submit = SubmitField('Upload')

app/data/__init__.py
"""
Qrater Data management.

Construction of blueprint
"""

from flask import Blueprint

bp = Blueprint('data', __name__)

from app.data import routes

app/data/routes.py
"""
Qrater Data Management.

Module with blueprint specific routes
"""

import os
import re
from flask import (render_template, flash, redirect, url_for, request,
                   current_app)
from flask_login import login_required, current_user
from app import db
from app.data import bp
from app.models import Dataset, Rater, Precomment
from app.data.functions import load_data, upload_data
from app.data.forms import LoadDatasetForm, UploadDatasetForm, EditDatasetForm
from app.data.exceptions import (OrphanDatasetError, EmptyLoadError)


@bp.route('/upload-dataset', methods=['GET', 'POST'])
@login_required
def upload_dataset():
    """Page to upload new dataset of MRI."""
    data_dir = os.path.join(current_app.config['ABS_PATH'],
                            'static/datasets/uploaded')

    # All raters
    all_raters = request.args.get('all_raters', 0, type=int)

    form = UploadDatasetForm()
    if form.validate_on_submit():
        files = request.files.getlist(form.dataset.name)
        savedir = os.path.join(data_dir, form.dataset_name.data)

        # If savedir does not exist; create it
        if not os.path.isdir(savedir):
            os.makedirs(savedir)

        # Form checks that dataset does not exist already
        # so there is no need to check here; just create it
        dataset = Dataset(name=form.dataset_name.data,
                          creator=current_user,
                          private=form.privacy.data)
        dataset.grant_access(current_user)
        db.session.add(dataset)

        privacy = 'a PRIVATE' if dataset.private else 'an OPEN'
        flash(f"{dataset.name} was created as {privacy} dataset", 'info')

        if len(files) > 10:
            # Redis can't handle FileStorage
            # First upload all files
            files_uploaded = upload_data(files, savedir)
            current_user.launch_task('load_data',
                                     f'Uploading {len(files)} new images '
                                     f'to {dataset.name} dataset...',
                                     icon='upload',
                                     alert_color='primary',
                                     files=files_uploaded,
                                     dataset_name=dataset.name,
                                     new_dataset=True)
            db.session.commit()
        else:
            try:
                # Function returns number of uploaded images
                loaded_imgs = load_data(files, dataset, savedir=savedir)
            except OrphanDatasetError:
                # If orphaned dataset, delete it
                db.session.delete(dataset)
            else:
                # If not, that means at least one image was uploaded
                # flash success with number of uploads
                flash(f'{loaded_imgs} file(s) successfully loaded!', 'success')
            finally:
                # Commit changes in database
                db.session.commit()

        return redirect(url_for('main.dashboard', all_raters=all_raters))
    for _, error in form.errors.items():
        flash(error[0], 'danger')
    return render_template('data/upload_dataset.html', form=form,
                           all_raters=all_raters, title='Upload Dataset')


@bp.route('/load-dataset', methods=['GET', 'POST'])
@bp.route('/load-dataset/<directory>', methods=['GET', 'POST'])
@login_required
def load_dataset(directory=None):
    """Page to load new datasets from within HOST."""
    data_dir = os.path.join(current_app.config['ABS_PATH'],
                            'static/datasets/preloaded')

    # All raters
    all_raters = request.args.get('all_raters', 0, type=int)

    # Choices of directories to load in form
    dir_choices = [d for d in os.listdir(data_dir)
                   if os.path.isdir(os.path.join(data_dir, d))]
    dir_choices.sort()

    info = {'directory': directory, 'new_imgs': 0}
    if directory is not None:
        # Save useful info for jinja template
        info['model'] = Dataset.query.filter_by(name=directory).first()
        # Check access before loading files
        if info['model']:
            info['access'] = current_user.has_access(info['model'])
            info['saved_imgs'] = info['model'].images.count()
        else:
            info['access'] = True
            info['saved_imgs'] = 0

        if info['access']:
            # Count the files in the directory
            all_files = []
            for root, _, files in os.walk(os.path.join(data_dir, directory)):
                all_files.extend([os.path.join(root, f)
                                  for f in files if not f.startswith('.')])
            info['new_imgs'] = len(all_files) - info['saved_imgs']

    form = LoadDatasetForm()
    form.dir_name.choices = dir_choices

    # Form submission must be restricted by access in template
    if form.validate_on_submit():
        if info['model']:
            new_dataset = False
        else:
            # If dataset is not a Dataset Model (does not exist), create it
            info['model'] = Dataset(name=form.dir_name.data,
                                    creator=current_user)
            db.session.add(info['model'])
            new_dataset = True
            flash(f"{info['model'].name} was created as an OPEN dataset",
                  'info')

        if len(all_files) > 10:
            current_user.launch_task('load_data',
                                     f"Loading {info['new_imgs']} new images "
                                     f"to {info['model'].name} dataset...",
                                     icon='load',
                                     alert_color='primary',
                                     files=all_files,
                                     dataset_name=info['model'].name,
                                     new_dataset=new_dataset,
                                     ignore_existing=True)
            db.session.commit()

        else:
            try:
                # Function returns number of uploaded images
                loaded_imgs = load_data(all_files, dataset=info['model'],
                                        host=True, new_dataset=new_dataset)

            except OrphanDatasetError:
                # If orphaned dataset, delete it
                # TODO this somehow throws an error; look into this
                # db.session.delete(info['model'])
                flash('No new files were successfully loaded '
                      'leaving the dataset empty', 'warning')

            else:
                if not new_dataset and loaded_imgs == 0:
                    flash('No new files were successfully loaded', 'warning')
                else:
                    flash(f'{loaded_imgs} file(s) successfully loaded!',
                          'success')
            finally:
                # Commit changes in database
                db.session.commit()

        return redirect(url_for('main.dashboard', all_raters=all_raters))

    # Form validation errors
    for _, error in form.errors.items():
        flash(error[0], 'danger')

    return render_template('data/load_dataset.html', form=form,
                           title="Load Dataset", dictionary=info,
                           all_raters=all_raters)


@bp.route('/edit-dataset', methods=['GET', 'POST'])
@bp.route('/edit-dataset/<dataset>', methods=['GET', 'POST'])
@login_required
def edit_dataset(dataset=None):
    """Page to edit an existing dataset of MRI."""
    data_dir = os.path.join(current_app.config['ABS_PATH'], 'static/datasets')

    # All raters
    all_raters = request.args.get('all_raters', 0, type=int)

    # Read-only; Disable dataset loader when accessing through link
    ro = request.args.get('ro', 0, type=int)

    ds_model = Dataset.query.\
        filter_by(name=dataset).\
        first_or_404() \
        if dataset else None

    form = EditDatasetForm()
    if ro:
        form.dataset.data = dataset

    privacy = ds_model.private if ds_model else None
    public_ds = Dataset.query.filter_by(private=False)
    private_ds = Dataset.query.filter(Dataset.viewers.contains(current_user))
    form.dataset.choices = [ds.name for ds in public_ds.union(private_ds)]
    form.viewers.choices = [(r.id, r.username, r in ds_model.viewers)
                            for r in Rater.query.order_by('username')
                            if r not in [current_user, ds_model.creator]] \
        if dataset else []

    # Test image names for regex helper
    test_names = {}
    for set in Dataset.query.all():
        test_names[set.name] = [img.path for img in set.images.limit(5).all()]

    changes = False
    subratings = ds_model.subratings if ds_model else None
    if form.validate_on_submit():
        new_ds_name = None

        # Subratings;
        if form.sr_change.data:
            sr_ids, sr_texts, sr_ratings, sr_keybindings = (
                [id.split("_")[1] if id else ""
                 for id in form.sr_ids.data.split("___")],
                form.sr_texts.data.split("___"),
                form.sr_ratings.data.split("___"),
                form.sr_keybindings.data.split("___")
            )

            # Sanity check
            print(f"{sr_ids=} {sr_texts=} {sr_ratings=} {sr_keybindings=}")
            if not (len(sr_ids)
                    == len(sr_texts)
                    == len(sr_ratings)
                    == len(sr_keybindings)):
                flash(('Something went wrong trying to set up the '
                      'pre-defined ratings.'), 'danger')
                return redirect(request.url)

            for n, id in enumerate(sr_ids):
                if "d" in id:
                    print(f"{id=}")
                    sr = Precomment.query.filter_by(id=id[1:-1]).first()
                    print(f"{sr=}")
                    if sr:
                        db.session.delete(sr)
                else:
                    sr = Precomment(dataset=ds_model) if "n" in id \

app/templates/data/confirm_delete_modal.html
<div
  class="modal fade"
  id="deleteConfirmModal"
  tabindex="-1"
  aria-labelledby="deleteConfirmModalLabel"
  aria-hidden="true"
  >
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-danger">
        <h3 class="modal-title text-white" id="deleteConfirmModalLabel">
          Delete Confirmation
        </h3>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
          ></button>
      </div>
      <div class="modal-body">
        <p>You are about to delete <span class="fw-bolder">{{ dataset }}</span>
          dataset. This will affect all Raters.</p>
        <p>The ratings won't be able to be recovered, so only do this if you
        are<br><span class="lead text-uppercase">absolutely sure</span>.</p>
        <p>A lot of people could get mad with you...</p>
      </div>
      <div class="modal-footer">
        <button
          type="button"
          class="btn btn-secondary"
          data-bs-dismiss="modal"
          >Cancel</button>
        <div class="btn-group">
          <a
            class="btn btn-danger"
            role="button"
            href="{{ url_for('data.delete_dataset', dataset=dataset) }}"
            >Delete Dataset</a>
          <button
            type="button"
            class="btn btn-danger dropdown-toggle dropdown-toggle-split"
            data-bs-toggle="dropdown"
            aria-expanded="false"
            ><span class="visually-hidden">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item"
                 href="{{ url_for('data.delete_dataset', dataset=dataset, keep_imgs=1) }}"
                 >Delete ratings (keep images)</a>
            </li>
            <li>
              <a class="dropdown-item"
                 href="{{ url_for('data.delete_dataset', dataset=dataset) }}"
                 >Delete dataset (ratings &amp; images)</a>
            </li>
            <li>
              <a class="dropdown-item"
                 href="{{ url_for('data.delete_dataset', dataset=dataset, nuke=1) }}"
                 >Delete ALL (ratings &amp; images &amp; FILES)</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/templates/data/load_dataset.html
{% extends "base.html" %}

{% block breadcrumb %}
<ol class="breadcrumb m-0">
  <li class="breadcrumb-item">
    <a
      class="text-decoration-none text-light"
      href="{{ url_for('main.dashboard') }}"
      >Dashboard</a>
  </li>
  <li class="breadcrumb-item">
    <a
      class="text-decoration-none text-light"
      href="#"
      >Load Data</a>
  </li>
</ol>
{% endblock %}

{% block app_content %}
  <h1>Load Dataset</h1>
  <form
    class="form"
    id="datasetForm"
    action=""
    method="POST"
    role="form"
  >
    {{ form.csrf_token() }}
    <div class="col-lg-9">
      <div class="row my-3 mx-0">
        <div class="col">
          <select
            class="form-select form-select-lg"
            id="datasetSelect"
            name="dir_name"
            aria-label="Select a dataset directory"
            >
            <option value="">Select a directory to load</option>
            {%- for dir in form.dir_name.choices -%}
            <option
              {% if dir == dictionary['directory'] %}selected{% endif %}
              >{{ dir }}</option>
            {%- endfor -%}
          </select>
        </div>
        <div
          id="dirInfo"
          class="form-text px-3 fs-6"
          >
          {% if dictionary['directory'] is none %}
          {% elif not dictionary['access'] %}
          <span
            class="text-danger"
            >Private Dataset: You don't have access to this dataset</span>
          {% elif dictionary['model'] is none %}
          <span
            class="text-primary"
            >Dataset Not Loaded: {{ dictionary['new_imgs'] }} unloaded files</span>
          {% elif dictionary['new_imgs'] == 0 %}
          <span
            class="text-success"
            >Loaded Dataset: {{ dictionary['saved_imgs'] }} images</span>
          {% elif dictionary['new_imgs'] > 0 %}
          <span
            class="text-success"
            >Loaded Dataset: {{ dictionary['saved_imgs'] }} images;</span>
          <span
            class="text-primary"
            > {{ dictionary['new_imgs'] }} unloaded files</span>
          {% endif %}
        </div>
      </div>
    </div>
    <button
      class="btn btn-primary btn-lg"
      id="submitBtn"
      type="submit"
      form="datasetForm"
      value="Load"
      {% if dictionary['directory'] is none
            or dictionary['new_imgs'] == 0
            or not dictionary['access'] -%}
      disabled
      {%- endif %}
      >Load Data</button>
  </form>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
  $(document).ready(function () {
    $("#datasetSelect").change(function() {
      if($(this).val() == "") {
        $("#datasetForm :input").attr("disabled", true);
        $(this).attr("disabled", false);
        $("#dirInfo").addClass("d-none");
      } else {
        $("#dirInfo").removeClass("d-none");
        window.location.href = "{{ url_for('data.load_dataset') }}/" +
          $(this).val();
      }
    });
    $("#datasetForm").submit(function() {
      $("#submitBtn").html(
        `<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Loading...`
      );
      $("#datasetForm :input").prop("readonly", true);
    });
  });
</script>
{% endblock %}

app/templates/data/upload_dataset.html
{% extends "base.html" %}

{% block breadcrumb %}
<ol class="breadcrumb m-0">
  <li class="breadcrumb-item">
    <a
      class="text-decoration-none text-light"
      href="{{ url_for('main.dashboard') }}"
      >Dashboard</a>
  </li>
  <li class="breadcrumb-item">
    <a
      class="text-decoration-none text-light"
      href="#"
      >Upload Dataset</a>
  </li>
</ol>
{% endblock %}

{% block app_content %}
  <h1>Upload New Dataset</h1>
  <form
    class="form"
    id="datasetForm"
    action=""
    method="POST"
    role="form"
    enctype="multipart/form-data"
  >
    {{ form.csrf_token() }}
    <div class="col-lg-9">
      <div class="row my-3 mx-0">
        <div class="col">
          <div class="form-floating">
            <input
              type="text"
              class="form-control"
              id="dataset_name"
              name="dataset_name"
              required
              placeholder="Dataset Name"
              >
            <label for="dataset_name">
              Dataset name
            </label>
          </div>
        </div>
      </div>
      <div class="row mb-3 mx-0">
        <label
          class="col-sm-12 col-md-3 col-form-label"
          for="uploadImgs"
          >MRI files</label>
        <div class="col-sm-12 col-md-9" id=uploadImgs>
          <input
            type="file"
            class="form-control"
            id="dataset"
            name="dataset"
            required
            multiple>
        </div>
      </div>
      <div class="row mb-3 mx-0">
        <label
          class="col-sm-12 col-md-3 col-form-label"
          for="privacyBool"
          >Privacy</label>
        <div class="col-sm-12 col-md-9" id="privacyBool">
          <div class="form-check form-check-inline ps-0">
            <div class="btn-group" role="group">
              <input
                type="radio"
                class="btn-check"
                name="privacy"
                id="openBtn"
                value="false"
                autocomplete="off"
                checked
                >
              <label
                class="btn btn-outline-primary"
                for="openBtn"
                >Open Dataset</label>
              <input
                type="radio"
                class="btn-check"
                name="privacy"
                id="privateBtn"
                value="true"
                autocomplete="off"
                >
              <label
                class="btn btn-outline-dark"
                for="privateBtn"
                >Private Dataset</label>
            </div>
          </div>
        </div>
      </div>
    </div>
    <button
      class="btn btn-primary btn-lg"
      id="submitBtn"
      type="submit"
      form="datasetForm"
      value="Upload"
      >Upload</button>
  </form>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
  $(document).ready(function () {
    $("#datasetForm").submit(function() {
      $("#submitBtn").html(
        `<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Loading...`
      );
      $("#datasetForm :input").prop("readonly", true);
    });
  });
</script>
{% endblock %}